language: rust
cache: cargo

rust:
  - stable
#  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

before_install:
  - set -e
  - sudo apt-get update

script: cargo build

notifications:
  email:
    on_success: never