[dependencies]
clap = '2.29.2'
git2 = '0.6'
glob = '0.2.11'
libcalcver = '0.2.0-beta.3'
serde_derive = '1.0'
toml = '0.4'

[package]
authors = [
    'Jerahmeel Cosinas <me@jerahmeelcosinas.net>',
    'Joelle Ortiz <contact@joelleortiz.me>',
]
name = 'calcver'
version = '0.1.0-alpha.12'
